version: 2.1

jobs:
  test-xcode-10:
    executor: xcode-10
    steps:
      - setup
      - run-tests

  test-xcode-9:
    executor: xcode-9
    steps:
      - setup
      - run-tests

  check-podspec:
    executor: xcode-10
    steps:
      - setup
      - cocoapods-specs
      - run: bundle exec pod lib lint

  deploy-to-cocoapods:
    executor: xcode-10
    steps:
      - setup
      - cocoapods-specs
      - run: bundle exec pod trunk push

commands:
  setup:
    description: "Shared setup"
    steps:
      - checkout
      - restore-gems

  restore-gems:
    description: "Restore Ruby Gems"
    steps:
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  cocoapods-specs:
    description: "Fetch CocoaPods Specs"
    steps:
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
  
  run-tests:
    description: "Runs the tests"
    steps:
      - run: mkdir -p build
      - run:
          name: "Run tests"
          command: |
            xcodebuild -project 'RZBluetooth.xcodeproj' -scheme 'RZBluetooth' \
            clean build test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' \
            CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= | tee build/xcode_raw_tests.log \
            | xcpretty --color --report junit --output build/xcode/results.xml
      - run:
          name: "Run tests"
          command: |
            xcodebuild -workspace 'RZBluetoothExample/RZBluetoothExample.xcworkspace' -scheme 'RZBluetoothExample' \
            clean build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' \
            CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= | tee build/xcode_raw_example.log \
            | xcpretty --color
      - store_test_results:
          path: build
      - store_test_results:
          path: build

executors:
  xcode-10:
    working_directory: /Users/distiller/project
    macos:
      xcode: "10.0.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -o pipefail

  xcode-9:
    working_directory: /Users/distiller/project
    macos:
      xcode: "9.4.1"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -o pipefail

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - check-podspec:
          filters:
            tags:
              only: /.*/
      - test-xcode-10:
          filters:
            tags:
              only: /.*/
      - test-xcode-9:
          filters:
            tags:
              only: /.*/
      - deploy-to-cocoapods:
          requires:
            - test-xcode-10
            - test-xcode-9
            - check-podspec
          filters:
            tags:
              only: /\d+(\.\d+)*(-.*)*/
            branches:
              ignore: /.*/
